# -*- coding: utf-8 -*-
"""pred_video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEu_oIMe78st_D2HT3DiG9_R9bx7oo1w
"""

from google.colab import output
!pip install ultralytics
!pip install supervision
!pip install lapx
output.clear()

import os
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
#from matplotlib.pyplot import figure
from ultralytics import YOLO
import supervision as sv

model = YOLO('yolov8m.pt')

# Монтируем Гугл Диск

import os
# from IPython.display import Image

from google.colab import drive # Подключаем диск
drive.mount('/content/drive')

# Здесь код для копирования нашей обученной модели с гугл-диска в коллаб.
# У нее достаточно небольшой вес, поэтому можно загрузить прямо с гугл-диска, копировать в коллаб необязательно

model_path = '/content/drive/MyDrive/Colab Notebooks/UII/internship_safe _head/weights/best-3_classes-m-a100 (2).pt'
model = YOLO(model_path)

results = model.predict(source="/content/drive/MyDrive/Colab Notebooks/UII/internship_safe _head/trim-video-online.com_1705759881_ЦОД12202309061633347_WMskO0lK.avi", save=True, conf=0.5, stream=True, show=False)

for r in results:
    next(results)

### Демонстрация видео в коллабе:


import moviepy
from moviepy.editor import *
from moviepy.editor import VideoFileClip
from IPython.display import display, clear_output

# Загрузка видеофайла
clip = VideoFileClip("/content/runs/detect/predict/trim-video-online.com_1705759881_ЦОД12202309061633347_WMskO0lK.avi")

# Преобразование файла в формат mp4
clip.write_videofile("temp.mp4")

# Освобождение ресурсов
clip.close()

# Воспроизведем видео в формате mp4 по указанному пути:

# ipython_display('/content/temp.mp4')

video_clip = VideoFileClip('/content/temp.mp4')
duration = video_clip.duration

# Увеличим 'maxduration' (в секундах) при вызове ipython_display
ipython_display('/content/temp.mp4', maxduration=duration + 10)



# Очистка мусора из ОЗУ

import gc
gc.collect()

